name: hotel-clustering
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.13.*
  - scikit-learn=1.4.*
  - matplotlib=3.8.*
  - seaborn=0.13.*
  - jupyter
  - jupyterlab
  - nbconvert
  - ipykernel
  - pip:
      - kaggle==1.6.*
